<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>BGFX</RootNamespace>
    </PropertyGroup>

   <ItemGroup>
        <Content Include="$(MSBuildThisFileDirectory)\Native\osx-arm64\libBGFX.dylib">
            <TargetPath>Runtime/osx-arm64/libBGFX.dylib</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
        <Content Include="$(MSBuildThisFileDirectory)\Native\win-x64\BGFX.dll">
            <TargetPath>Runtime/win-x64/BGFX.dll</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </Content>
    </ItemGroup>


</Project>
